create database java_mobile;
use java_mobile;

INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, SEX, ROLE, E_MAIL, PASSWORD, PHONE, ADDRESS, MOD_BY, CREATE_DATE, MOD_DATE) 
VALUES (1, 'Admin', 'ADMIN', 'M', 1, 'admin@gmail.com', '1234', '', '', 1, NOW(), NOW())

INSERT INTO CONFIGURATION (CONFIGURATION_ID, NAME, VALUE, DESCRIPTION, CREATE_DATE,MOD_DATE,MOD_BY) VALUES 
(1, 'UNIT_PRICE', '200', 'PRIX UNITAIRE', NOW(), NOW(), 1) 